config/routes.rb
Medusa::Application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-status/web'
  mount Sidekiq::Web, at:'/sidekiq', as: 'sidekiq'
  get "surfaces/index"
  get "surfaces/show"
  devise_for :users, controllers: {
               omniauth_callbacks: "users/omniauth_callbacks",
               registrations: "users"
             }
  resources :tokens, only: :create

  root 'records#index'
  get '/front/vue', to: 'front#vue'

  concern :bundleable do
    collection do
      post :bundle_edit
      post :bundle_update
    end
  end

  concern :reportable do
    member do
      get :download_card
      get :download_label
    end
    collection do
      get :download_bundle_card
      get :download_bundle_label
      get :download_bundle_list
    end
  end

  concern :link_by_global_id do
    collection do
      post :link_by_global_id
    end
  end

  concern :inventory do
    member do
      post :inventory
    end
  end

  concern :multiple do
    collection do
      get :multiple_new
      post :multiple_create
    end
  end

  concern :sesar_upload do
    member do
      post :sesar_upload
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :records, only: %i[show]
      resources :spots
      resources :surfaces do
        resources :spots, concerns: [:link_by_global_id], only: [:index, :show, :create, :update, :destroy], controller: "surface_spots"
      end
    end
  end

  resources :records, { id: /((?!\.(html$|json$|xml$|pml$)).)*/ } do
    member do
      get 'record_property' => 'records#property'
      get 'casteml'
      get 'ancestors'
      get 'descendants'
      get 'self_and_descendants'
      get 'pmlame'
      get 'root'
      get 'parent'
      get 'daughters'
      get 'siblings'
      get 'self_and_siblings'
      get 'families'
      put :dispose
      patch :dispose
      put :restore
      patch :restore
      put :lose
      patch :lose
      put :found
      patch :found
      put :publish
      patch :publish
    end
  end

  resources :specimens, concerns: [:bundleable, :reportable, :sesar_upload], except: [:new] do
    member do
      get :quantity_history
      get :family
      get :picture
      get :map
      get :property
      get :detail_edit
      get :chemistries
      get :place, action: :show_place
      post :place, action: :create_place
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "specimen" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "specimen" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "specimen" }
    resources :daughters, concerns: [:link_by_global_id], only: [:index, :create,:update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "specimen" }
    resources :surfaces, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/surfaces", defaults: { parent_resource: "specimen" }
  end

  resources :divide_specimens, only: [:update] do
    member do
      put :loss
    end
  end

  resources :divides, only: [:edit, :update, :destroy] do
    member do
      put :loss
    end
  end

  resources :paths, only: [:update]

  resources :boxes, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :property
      get :tree_node
      get :list_for_print
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "box" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "box" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "box" }
    resources :specimens, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "box", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "box", association_name: "children" }
  end

  resources :places, concerns: [:bundleable, :reportable] do
    member do
      get :map
      get :property
    end
    collection do
      post :import
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "place" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id],only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "place" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "place" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "place", association_name: "specimens" }
  end

  resources :analyses, concerns: :bundleable do
    member do
      get :picture
      get :property
      get :casteml
    end
    collection do
      post :import
      get :table
      get :castemls
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "analysis" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "analysis" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "analysis" }
    resources :chemistries, concerns: [:multiple],only: [:index, :create, :update, :destroy], controller: "nested_resources/chemistries"
  end

  resources :bibs, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :map
      get :property
      get :specimens_detail
      put :publish
    end
    collection do
      get :download_to_tex
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "bib" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "bib", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "bib", association_name: "boxes" }
    resources :places, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/places", defaults: { parent_resource: "bib", association_name: "places" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "bib", association_name: "analyses" }
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "bib" }
    resources :tables, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/tables", defaults: { parent_resource: "bib" }
    resources :surfaces, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/surfaces", defaults: { parent_resource: "bib" }
  end

  resources :surfaces, concerns: [:bundleable, :reportable] do
    member do
      get :family
      get :picture
      get :property
      get :map
      get :layer
      get :image
      get :show_bibs
      get :show_specimens
      get :show_spot_specimens
      post 'tiles'
      post 'scale'
    end
    resources :images, concerns: [:link_by_global_id], only: [:index, :show, :create, :update, :destroy], controller: "surface_images" do
      member do
        get :family
        get :svg
        get :zooms
        get :map
        get :fits_image
        post 'move_to_top'

app/controllers/bibs_controller.rb
class BibsController < ApplicationController
  respond_to :html, :xml, :json
  before_action :find_resource, except: [:index, :create, :bundle_edit, :bundle_update, :download_bundle_card, :download_label, :download_bundle_label, :download_to_tex]
  before_action :find_resources, only: [:bundle_edit, :bundle_update, :download_bundle_card, :download_bundle_label, :download_to_tex]
  load_and_authorize_resource

  def index
    @search = Bib.includes(bib_authors: :author).readables(current_user).order("bib_authors.priority").ransack(params[:q])
    @search.sorts = "updated_at DESC" if @search.sorts.empty?
    @bibs = @search.result.page(params[:page]).per(params[:per_page])
    respond_with @bibs
  end

  def show
    respond_with @bib
  end

  def specimens_detail
    respond_with @bib
  end

  def edit
    respond_with @bib, layout: !request.xhr?
  end

  def create
    @bib = Bib.new(bib_params)
    @bib.save
    respond_with @bib
  end

  def update
    @bib.update(bib_params)
    respond_with @bib
  end

  def publish
    #@bib.publish!
    PublishWorker.perform_async(@bib.global_id)
    respond_with @bib
  end
  
  def destroy
    @bib.destroy
    respond_with @bib
  end

  def family
    respond_with @bib, layout: !request.xhr?
  end

  def picture
    respond_with @bib, layout: !request.xhr?
  end
  
  def map
    respond_with @bib, layout: !request.xhr?
  end

  def property
    respond_with @bib, layout: !request.xhr?
  end

  def bundle_edit
    respond_with @bibs
  end

  def bundle_update
    @bibs.each { |bib| bib.update(bib_params.only_presence) }
    render :bundle_edit
  end

  def download_bundle_card
    method = (params[:a4] == "true") ? :build_a_four : :build_cards
    report = Bib.send(method, @bibs)
    send_data(report.generate, filename: "bibs.pdf", type: "application/pdf")
  end

  def download_label
    bib = Bib.find(params[:id])
    send_data(bib.build_label, filename: "bib_#{bib.id}.label", type: "text/label")
  end

  def download_bundle_label
    label = Bib.build_bundle_label(@bibs)
    send_data(label, filename: "bibs.label", type: "text/label")
  end
  
  def download_to_tex
    tex = Bib.build_bundle_tex(@bibs)
    send_data(tex, filename: "bibs.bib", type: "text")
  end

  private

  def bib_params
    params.require(:bib).permit(
      :entry_type,
      :abbreviation,
      :name,
      :journal,
      :year,
      :volume,
      :number,
      :pages,
      :month,
      :abstract,
      :summary,
      :note,
      :key,
      :link_url,
      :doi,
      :user_id,
      :group_id,
      :published,
      author_ids: [],
      record_property_attributes: [
        :id,
        :global_id,
        :user_id,
        :group_id,
        :owner_readable,
        :owner_writable,
        :group_readable,
        :group_writable,
        :guest_readable,
        :guest_writable,
        :published,
        :lost
      ],
      bib_authors_attributes: [
        :id,
        :priority
      ]
    )
  end

  def find_resource
    @bib = Bib.includes({places: [:record_property]}, {analyses: [:record_property, :device, :chemistries]}, {tables: {analyses: [:device, :record_property, :chemistries]}}, {specimens: [:tags, :record_property, :attachment_files, :classification, :physical_form, :specimen_custom_attributes, {place: [:record_property]}, {box: [:record_property]}, {analyses: [:device, :record_property, :chemistries]}]}).find(params[:id]).decorate
  end

  def find_resources
    @bibs = Bib.where(id: params[:ids])
  end

end

app/controllers/nested_resources/bibs_controller.rb
class NestedResources::BibsController < ApplicationController

  respond_to :html, :xml, :json
  before_action :find_resource
  load_and_authorize_resource

  def index
    @bibs = @parent.bibs
    respond_with @bibs
  end

  def create
    @bib = Bib.new(bib_params)
    @parent.bibs << @bib if @bib.save
    respond_with @bib, location: adjust_url_by_requesting_tab(request.referer), action: "error"
  end

  def update
    @bib = Bib.find(params[:id])
    @parent.bibs << @bib
    respond_with @bib, location: adjust_url_by_requesting_tab(request.referer)
  end

  def destroy
    @bib = Bib.find(params[:id])
    @parent.bibs.delete(@bib)
    respond_with @bib, location: adjust_url_by_requesting_tab(request.referer)
  end

  def link_by_global_id
    @bib = Bib.joins(:record_property).where(record_properties: {global_id: params[:global_id]}).readonly(false).first
    @parent.bibs << @bib if @bib
    respond_with @bib, location: adjust_url_by_requesting_tab(request.referer), action: "error"
  rescue
    duplicate_global_id
  end

  private

  def bib_params
    params.require(:bib).permit(
      :entry_type,
      :abbreviation,
      :name,
      :journal,
      :year,
      :volume,
      :number,
      :pages,
      :month,
      :note,
      :key,
      :link_url,
      :doi,
      :user_id,
      :group_id,
      author_ids: [],
      record_property_attributes: [
        :global_id,
        :user_id,
        :group_id,
        :owner_readable,
        :owner_writable,
        :group_readable,
        :group_writable,
        :guest_readable,
        :guest_writable,
        :published,
        :published_at
      ]
    )
  end

  def find_resource
    resource_name = params[:parent_resource]
    resource_class = resource_name.camelize.constantize
    @parent = resource_class.find(params["#{resource_name}_id"])
  end

  def duplicate_global_id
    respond_to do |format|
      format.html { render "parts/duplicate_global_id", status: :unprocessable_entity }
      format.all { render body: nil, status: :unprocessable_entity }
    end
  end

end

app/views/bibs/_specimen.html.erb
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">        
  <div class="pull-right">
    <%= link_to 'more', specimens_detail_bib_path(@bib) %>
  </div>
</div>
</div>
<div class="row">
<%= form_with url:bundle_edit_specimens_path, id: "specimen-bundle-form" do %>
<% specimen_groups = @bib.specimens.group_by{|specimen| specimen.box} %>
<% specimen_groups.each do |box, specimens| %>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<div class="panel panel-default">
    <div class="panel-heading">
    <% if box %>
        <%= link_to box.decorate.name_with_id, box_path(box) %>
        <%# links = [content_tag(:div, qrcode(box.global_id, size: "80x80"), class: "col-xs-2 col-sm-2 col-md-2 col-lg-2") ] %>
        <% links = [] %>
        <%# box.related_spots.each do |spot| %>
        <%# svg_link = link_to(spot_path(spot)) do %>
          <%# spot.attachment_file.decorate.picture_with_spots(width:120, height:90, spots:[spot]) %>
        <%# end %>
          <%# links << content_tag(:div, svg_link, class: "col-xs-2 col-sm-2 col-md-2 col-lg-2") %>
        <%# end %>
        <%#= content_tag(:div, raw( links.join ), class: "row spot-thumbnails") %>
    <% end %>
    </div>
    <table class="table table-condensed">
      <% specimens.each do |specimen| %>
      <% specimen = specimen.decorate %>
      <tr>
      <td class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
          <%#= qrcode specimen.global_id, size: "80x80" %>
          <%= link_to specimen.attachment_files.first.decorate.picture(width: 160, height: 160, type: :thumb), specimen, class: specimen_ghost(specimen) if specimen.attachment_files.present? %>
          <%= check_box_tag("ids[]", specimen.id, true, {id: "ids_#{specimen.id}", class: "select-row"}) if can?(:update, specimen) %>
          <%= link_to bib_specimen_path(@bib, specimen) + tab_param(__FILE__), method: :delete, title: "unlink specimen", data: {confirm: t("confirm.unlink")} do %>
            <span class="fas fa-times"></span>
          <% end %>
      </td>
      <td class="col-xs-10 col-sm-10 col-md-10 col-lg-10">

        <%= specimen.name_with_id(true) %>
        <ul>
          <% unless specimen.igsn.blank? %>
            <li>
              IGSN: <%= link_to specimen.igsn, Settings.sesar_url(igsn: specimen.igsn) %>
          <%= link_to Settings.sesar_url(igsn: specimen.igsn, edit: true), title: "edit on SESAR" do %>
            <span class="fas fa-pencil-alt"></span>
          <% end %>

            </li>
          <% end %>
          <% if specimen.rplace %>
            <% place = specimen.rplace.decorate %>
            <li>
              place: <%= raw(place.try!(:latitude_to_html)) + ", " + raw(place.try!(:longitude_to_html)) %> <%= link_to "more", place_path(place) %>
            </li>
          <% end %>
          <%= li_if_exist("classification: ", specimen.classification.try!(:full_name)) %>
          <%= li_if_exist("physical-form: ", specimen.physical_form.try!(:name)) %>
          <%= li_if_exist("quantity (#{specimen.quantity_unit}): ", specimen.quantity) %>
          <%= content_tag(:li, "status: #{specimen.status_icon} (#{specimen.status_name})", {}, false) if specimen.status_name.present? %>
          <%= li_if_exist("age (#{specimen.age_unit}): ", specimen.age_in_text) %>
          <%#= li_if_exist("tag list: ", specimen.tags.pluck(:name).join(', ')) %>
          <%= li_if_exist("description: ", specimen.description) %>
          <% specimen.specimen_custom_attributes.each do |specimen_custom_attribute| %>
            <%= li_if_exist("#{specimen_custom_attribute.custom_attribute.name}: ", specimen_custom_attribute.value ) %>
          <% end %> 
          <li>modified at <%= difference_from_now(specimen.updated_at) %></li>
        </ul>      
      </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>
<% end %>
<% end %>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<%= link_to content_tag(:span, nil, class: "fas fa-pencil-alt"), '#', onclick: "$('#specimen-bundle-form').submit();", class: "btn btn-default", title: "open multi-edit page with checked items" %>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
    </div>
    <table class="table table-condensed">
      <tr>
      <td class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <%= form_with url:link_by_global_id_bib_specimens_path(@bib), method: :post do %>
          <%= hidden_tabname_tag(__FILE__) %>
            <div class="input-group"> 
            <%= text_field_tag :global_id, nil, id: "specimen-global-id", :placeholder => "input ID", class: "form-control input-sm" %>
            <span class="input-group-addon">
              <%= link_to specimens_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#specimen-global-id" do %>
                <span class="fas fa-search"></span>
              <% end %>
            </span>

            </div>
              <%= button_tag title: "link specimen by global id", class: "btn btn-default" do %>
                <span class="far fa-save"></span>
              <% end %>
        <% end %>
      </td>
      <td class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <%= form_with model:Specimen.new, url: bib_specimens_path(@bib) do |f|%>
            <%= hidden_tabname_tag(__FILE__) %>
            <%= f.text_field :name, :placeholder => "input name", class: "form-control input-sm" %>
            <%= f.select :physical_form_id, PhysicalForm.pluck(:name, :id), { prompt: "select physical form" }, class: "form-control input-sm" %>
            <%= f.text_field :quantity, :placeholder => "input quantity", class: "form-control input-sm" %>
            <%= f.text_field :quantity_unit, :placeholder => "input quantity unit", class: "form-control input-sm" %>
              <%= f.button title:"add specimen file", class: "btn btn-default" do %>
                <span class="far fa-save"></span>
              <% end %>
          <% end %>
      </td>
      </tr>
    </table>
  </div>
</div>

</div>
<%= mantra "To let join, fill ID field and press save button.  To create new, fill fields and press save button.", :title => "#{@alias_specimen.capitalize}s related to bibliography" %>

app/views/bibs/property.html.erb
<%= render partial: "parts/property", locals: { record: @bib } %>

<%= javascript_tag do %>
  $(document).on("succeed.ajaxForm", "#edit_bib_<%= @bib.id %>", function() {
    location.href="<% bib_path(@bib) %>";
  });
<% end %>

app/views/bibs/specimens_detail.html.erb
<div class="row">
  <div id="show-caption" class="col-lg-12">
    <%= link_to show_title(@bib), bib_path(@bib) %>
  </div>
</div>

<div class="row">

<%= form_with url:bundle_edit_specimens_path, id: "specimen-bundle-form" do %>
<% specimen_groups = @bib.specimens.group_by{|specimen| specimen.box} %>
<% specimen_groups.each do |box, specimens| %>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
    <% if box %>
        <%= box.decorate.box_path_with_id %>
        <%# links = [content_tag(:div, qrcode(box.global_id, size: "80x80"), class: "col-xs-2 col-sm-2 col-md-2 col-lg-2") ] %>
        <% links = [] %>
        <% box.related_spots.each do |spot| %>
        <% svg_link = link_to(spot_path(spot)) do %>
          <% spot.attachment_file.decorate.picture_with_spots(width:120, height:90, spots:[spot]) %>
        <% end %>
          <% links << content_tag(:div, svg_link, class: "col-xs-2 col-sm-2 col-md-2 col-lg-2") %>
        <% end %>
        <%= content_tag(:div, raw( links.join ), class: "row spot-thumbnails") %>
    <% end %>
    </div>
    <table class="table table-condensed">
      <% specimens.each do |specimen| %>
      <% specimen = specimen.decorate %>
      <tr>
      <td class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
          <%= qrcode specimen.global_id, size: "80x80" %>
          <%= check_box_tag("ids[]", specimen.id, true, {id: "ids_#{specimen.id}", class: "select-row"}) if can?(:update, specimen) %>
          <%= link_to bib_specimen_path(@bib, specimen) + tab_param(__FILE__), method: :delete, title: "unlink specimen", data: {confirm: t("confirm.unlink")} do %>
            <span class="fas fa-times"></span>
          <% end %>
      </td>
      <td class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        <%= link_to specimen.attachment_files.first.decorate.picture(width: 160, height: 160, type: :thumb), specimen, class: specimen_ghost(specimen) if specimen.attachment_files.present? %>
      </td>

      <td class="col-xs-7 col-sm-7 col-md-7 col-lg-7">

        <%= specimen.name_with_id(true) %>
        <ul>
          <% unless specimen.igsn.blank? %>
            <li>
              IGSN: <%= link_to specimen.igsn, Settings.sesar_url(igsn: specimen.igsn) %>
          <%= link_to Settings.sesar_url(igsn: specimen.igsn, edit: true), title: "edit on SESAR" do %>
            <span class="fas fa-pencil-alt"></span>
          <% end %>

            </li>
          <% end %>
          <% if specimen.rplace %>
            <% place = specimen.rplace.decorate %>
            <li>
              place: <%= raw(place.try!(:latitude_to_html)) + ", " + raw(place.try!(:longitude_to_html)) %> <%= link_to "more", place_path(place) %>
            </li>
          <% end %>
          <%= li_if_exist("classification: ", specimen.classification.try!(:full_name)) %>
          <%= li_if_exist("physical-form: ", specimen.physical_form.try!(:name)) %>
          <%= li_if_exist("quantity (#{specimen.quantity_unit}): ", specimen.quantity) %>
          <%= content_tag(:li, "status: #{specimen.status_icon} (#{specimen.status_name})", {}, false) if specimen.status_name.present? %>
          <%= li_if_exist("age (#{specimen.age_unit}): ", specimen.age_in_text) %>
          <%= li_if_exist("tag list: ", specimen.tag_list) %>
          <%= li_if_exist("description: ", specimen.description) %>
          <% specimen.specimen_custom_attributes.each do |specimen_custom_attribute| %>
            <%= li_if_exist("#{specimen_custom_attribute.custom_attribute.name}: ", specimen_custom_attribute.value ) %>
          <% end %> 
          <li>modified at <%= difference_from_now(specimen.updated_at) %></li>
        </ul>      
      </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>
<% end %>
<% end %>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<%= link_to content_tag(:span, nil, class: "fas fa-pencil-alt"), '#', onclick: "$('#specimen-bundle-form').submit();", class: "btn btn-default", title: "open multi-edit page with checked items" %>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
    </div>
    <table class="table table-condensed">
      <tr>
      <td class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <%= form_with url:link_by_global_id_bib_specimens_path(@bib), method: :post do %>
          <%= hidden_tabname_tag(__FILE__) %>
            <div class="input-group"> 
            <%= text_field_tag :global_id, nil, id: "specimen-global-id", :placeholder => "input ID", class: "form-control input-sm" %>
            <span class="input-group-addon">
              <%= link_to specimens_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#specimen-global-id" do %>
                <span class="fas fa-search"></span>
              <% end %>
            </span>

            </div>
              <%= button_tag title: "link specimen by global id", class: "btn btn-default" do %>
                <span class="far fa-save"></span>
              <% end %>
        <% end %>
      </td>
      <td class="col-xs-6 col-sm-6 col-md-6 col-lg-6">

          <%= form_with model:Specimen.new, url: bib_specimens_path(@bib) do |f|%>
            <%= hidden_tabname_tag(__FILE__) %>
            <%= f.text_field :name, :placeholder => "input name", class: "form-control input-sm" %>
            <%= f.select :physical_form_id, PhysicalForm.pluck(:name, :id), { prompt: "select physical form" }, class: "form-control input-sm" %>
            <%= f.text_field :quantity, :placeholder => "input quantity", class: "form-control input-sm" %>
            <%= f.text_field :quantity_unit, :placeholder => "input quantity unit", class: "form-control input-sm" %>
              <%= f.button title:"add specimen file", class: "btn btn-default" do %>
                <span class="far fa-save"></span>
              <% end %>
          <% end %>
      </td>
      </tr>
    </table>
  </div>
</div>

</div>
<%= mantra "To link an existing #{@alias_specimen} to the bib, fill in the column  ID. To upload a new #{@alias_specimen}, fill in the columns of name, physical-form, and quantity.", :title => "#{@alias_specimen}s related to the bib" %>