config/routes.rb
Medusa::Application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-status/web'
  mount Sidekiq::Web, at:'/sidekiq', as: 'sidekiq'
  get "surfaces/index"
  get "surfaces/show"
  devise_for :users, controllers: {
               omniauth_callbacks: "users/omniauth_callbacks",
               registrations: "users"
             }
  resources :tokens, only: :create

  root 'records#index'
  get '/front/vue', to: 'front#vue'

  concern :bundleable do
    collection do
      post :bundle_edit
      post :bundle_update
    end
  end

  concern :reportable do
    member do
      get :download_card
      get :download_label
    end
    collection do
      get :download_bundle_card
      get :download_bundle_label
      get :download_bundle_list
    end
  end

  concern :link_by_global_id do
    collection do
      post :link_by_global_id
    end
  end

  concern :inventory do
    member do
      post :inventory
    end
  end

  concern :multiple do
    collection do
      get :multiple_new
      post :multiple_create
    end
  end

  concern :sesar_upload do
    member do
      post :sesar_upload
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :records, only: %i[show]
      resources :spots
      resources :surfaces do
        resources :spots, concerns: [:link_by_global_id], only: [:index, :show, :create, :update, :destroy], controller: "surface_spots"
      end
    end
  end

  resources :records, { id: /((?!\.(html$|json$|xml$|pml$)).)*/ } do
    member do
      get 'record_property' => 'records#property'
      get 'casteml'
      get 'ancestors'
      get 'descendants'
      get 'self_and_descendants'
      get 'pmlame'
      get 'root'
      get 'parent'
      get 'daughters'
      get 'siblings'
      get 'self_and_siblings'
      get 'families'
      put :dispose
      patch :dispose
      put :restore
      patch :restore
      put :lose
      patch :lose
      put :found
      patch :found
      put :publish
      patch :publish
    end
  end

  resources :specimens, concerns: [:bundleable, :reportable, :sesar_upload], except: [:new] do
    member do
      get :quantity_history
      get :family
      get :picture
      get :map
      get :property
      get :detail_edit
      get :chemistries
      get :place, action: :show_place
      post :place, action: :create_place
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "specimen" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "specimen" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "specimen" }
    resources :daughters, concerns: [:link_by_global_id], only: [:index, :create,:update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "specimen" }
    resources :surfaces, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/surfaces", defaults: { parent_resource: "specimen" }
  end

  resources :divide_specimens, only: [:update] do
    member do
      put :loss
    end
  end

  resources :divides, only: [:edit, :update, :destroy] do
    member do
      put :loss
    end
  end

  resources :paths, only: [:update]

  resources :boxes, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :property
      get :tree_node
      get :list_for_print
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "box" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "box" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "box" }
    resources :specimens, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "box", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "box", association_name: "children" }
  end

  resources :places, concerns: [:bundleable, :reportable] do
    member do
      get :map
      get :property
    end
    collection do
      post :import
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "place" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id],only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "place" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "place" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "place", association_name: "specimens" }
  end

  resources :analyses, concerns: :bundleable do
    member do
      get :picture
      get :property
      get :casteml
    end
    collection do
      post :import
      get :table
      get :castemls
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "analysis" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "analysis" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "analysis" }
    resources :chemistries, concerns: [:multiple],only: [:index, :create, :update, :destroy], controller: "nested_resources/chemistries"
  end

  resources :bibs, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :map
      get :property
      get :specimens_detail
      put :publish
    end
    collection do
      get :download_to_tex
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "bib" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "bib", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "bib", association_name: "boxes" }
    resources :places, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/places", defaults: { parent_resource: "bib", association_name: "places" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "bib", association_name: "analyses" }
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "bib" }
    resources :tables, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/tables", defaults: { parent_resource: "bib" }
    resources :surfaces, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/surfaces", defaults: { parent_resource: "bib" }
  end

  resources :surfaces, concerns: [:bundleable, :reportable] do
    member do
      get :family
      get :picture
      get :property
      get :map
      get :layer
      get :image
      get :show_bibs
      get :show_specimens
      get :show_spot_specimens
      post 'tiles'
      post 'scale'
    end
    resources :images, concerns: [:link_by_global_id], only: [:index, :show, :create, :update, :destroy], controller: "surface_images" do
      member do
        get :family
        get :svg
        get :zooms
        get :map
        get :fits_image
        post 'move_to_top'

app/controllers/nested_resources/specimens_controller.rb
class NestedResources::SpecimensController < ApplicationController

  respond_to  :html, :xml, :json
  before_action :find_resource
  before_action :set_association_name
  load_and_authorize_resource

  def index
    @specimens = @parent.send(@association_name)
    respond_with @specimens
  end

  def create
    @specimen = Specimen.new(specimen_params)
    ActiveRecord::Base.transaction do
    	succeed = @parent.send(@association_name) << @specimen if @specimen.save
      raise ActiveRecord::Rollback unless succeed
    end
    respond_with @specimen, location: adjust_url_by_requesting_tab(request.referer), action: "error"
  end

  def update
    @specimen = Specimen.find(params[:id])
    @parent.send(@association_name) << @specimen
    respond_with @specimen
  end

  def destroy
    @specimen = Specimen.find(params[:id])
    @parent.send(@association_name).delete(@specimen)
    respond_with @specimen, location: adjust_url_by_requesting_tab(request.referer)
  end

  def link_by_global_id
    @specimen = Specimen.joins(:record_property).where(record_properties: {global_id: params[:global_id]}).readonly(false).first
    @parent.send(@association_name) << @specimen if @specimen
    respond_with @specimen, location: adjust_url_by_requesting_tab(request.referer), action: "error"
  rescue
    duplicate_global_id
  end

  def inventory
    @specimen = Specimen.find(params[:id])
    @specimen.update(box_id: params[:box_id])
    @specimen.paths.current.first.update_attribute(:checked_at, Time.now) if @specimen.paths.current.first
    respond_with @specimen
  end

  private

  def specimen_params
    params.require(:specimen).permit(
      :name,
      :physical_form_id,
      :classification_id,
      :quantity,
      :quantity_unit,
      :tag_list,
      :parent_id,
      :box_id,
      :place_id,
      :description,
      :igsn,
      :age_min,
      :age_max,
      :age_unit,
      :size,
      :size_unit,
      :collector,
      :collector_detail,
      :collected_at,
      :collection_dateprecision,
    record_property_attributes: [
        :global_id,
        :user_id,
        :group_id,
        :owner_readable,
        :owner_writable,
        :group_readable,
        :group_writable,
        :guest_readable,
        :guest_writable,
        :published,
        :published_at
      ]
    )
  end

  def find_resource
    resource_name = params[:parent_resource]
    resource_class = resource_name.camelize.constantize
    @parent = resource_class.find(params["#{resource_name}_id"])
  end

  def duplicate_global_id
    respond_to do |format|
      format.html { render "parts/duplicate_global_id", status: :unprocessable_entity }
      format.all { render body: nil, status: :unprocessable_entity }
    end
  end

  def set_association_name
    @association_name = (params[:association_name] ? params[:association_name] : :specimens)
  end
end

app/views/specimens/_analysis.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th>name</th>
      <th>device</th>
      <th></th>
      <th>global-id</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= form_with url:bundle_edit_analyses_path, id: "analysis-bundle-form" do %>
      <% @specimen.full_analyses.each do |analysis| %>
        <tr>
          <td>
            <%= check_box_tag("ids[]", analysis.id, false, {id: "ids_#{analysis.id}", class: "select-row"}) if can?(:update, analysis) %>
          </td>
          <td>
          <%= link_to_if(can?(:read, analysis), list_title(analysis), analysis_path(analysis)) %>
          <%= link_to_if(can?(:read, analysis), content_tag(:span, analysis.chemistries.size, class:"badge"), analysis_path(analysis, format: :modal), "data-toggle" => "modal", "data-target" => "#show-modal") %>
          <% unless analysis.specimen == @specimen %>
           on <%= link_to list_title(analysis.specimen), specimen_path(analysis.specimen) %>
          <% end %>
          </td>
          <td><%= analysis.device.try!(:name) %></td>
          <td></td>
          <td><%= analysis.try!(:global_id) %></td> 
          <td>
            <% if analysis.specimen == @specimen %>
            <%= link_to specimen_analysis_path(@specimen, analysis) + tab_param(__FILE__), method: :delete, title: "unlink analysis", data: {confirm: t("confirm.unlink")} do %>
              <span class="fas fa-times"></span>
            <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <%= form_with model:Analysis.new, url: specimen_analyses_path(@specimen) do |f|%>
        <%= hidden_tabname_tag(__FILE__) %>
        <th><%= check_box_tag nil, nil, false, class: "select-row-all" %></th>
        <th><%= f.text_field :name, class: "form-control input-sm" %></th>
        <th><%= f.select :device_id, Device.pluck(:name, :id), { include_blank: true }, class: "form-control input-sm" %></th>
        <th>
          <%= f.button title:"add analysis file",class: "btn btn-default" do %>
            <span class="far fa-save"></span>
          <% end %>
        </th>
      <% end %>
      <%= form_with url:link_by_global_id_specimen_analyses_path(@specimen), method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
        <th>
	  <div class="input-group">
	    <%= text_field_tag :global_id, nil, id: "analysis-global-id", class: "form-control input-sm" %>
	    <span class="input-group-addon">
	      <%= link_to analyses_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#analysis-global-id" do %>
	      <span class="fas fa-search"></span>
	      <% end %>
	    </span>
	  </div>
	</th>
        <th>
          <%= button_tag title: "link analysis by global id", class: "btn btn-default" do %>
            <span class="far fa-save"></span>
          <% end %>
        </th>
      <% end %>
    </tr>
  </tfoot>
</table>
<%= link_to content_tag(:span, nil, class: "fas fa-pencil-alt"), '#', onclick: "$('#analysis-bundle-form').submit();", class: "btn btn-default", title: "open multi-edit page with checked items" %>

<%= mantra "To let join, fill ID field and press save button.  To create new, fill fields and press save button.", :title => "Analysis data of <#{@specimen.name}>"  %>

app/views/specimens/_bib.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th colspan= "2">name</th>
      <th>global-id</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= form_with url:bundle_edit_bibs_path, id: "bib-bundle-form" do %>
      <% @specimen.full_bibs.each do |bib| %>
        <% bib = bib.decorate %>
        <tr>
          <td>
              <%= check_box_tag("ids[]", bib.id, checked: false, id: "ids_#{bib.id}", class: "select-row") if can?(:update, bib) %>
            </td>
          <td colspan="2">
            <%= link_to_if can?(:read, bib), content_tag(:span, nil, class: "fas fa-book") + raw(bib.to_html), bib %>
            <ul>
            <% bib.tables.each do |table| %>
              <% next unless @specimen.full_tables.include?(table) %>
              <li><%= link_to content_tag(:span, nil, class: "fas fa-table") + table.caption, table %></li>
              <% end %>
            </ul>
          </td>
          <td><%= bib.try!(:global_id) %></td>
          <td>
            <% if @specimen.bibs.include?(bib) %>
            <%= link_to specimen_bib_path(@specimen,bib) + tab_param(__FILE__), method: :delete ,title: "unlink bib",data: {confirm: t("confirm.unlink")} do %>
              <span class="fas fa-times"></span>
            <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
     <%= form_with model:Bib.new, url: specimen_bibs_path(@specimen) do |f|%>
        <%= hidden_tabname_tag(__FILE__) %>
        <th><%= check_box_tag nil, nil, false, class: "select-row-all" %></th>
        <th><%#= f.text_field :name, class: "form-control input-sm" %></th>
        <th>
          <%#= f.button title:"add bib",class: "btn btn-default" do %>
            <%#<span class="far fa-save"></span>%>
          <%# end %>
        </th>
      <% end %>
    <%= form_with url:link_by_global_id_specimen_bibs_path(@specimen), method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
        <th>
	  <div class="input-group">
	    <%= text_field_tag :global_id, "", id: "bib-global-id", class: "form-control input-sm" %>
	    <span class="input-group-addon">
	      <%= link_to bibs_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#bib-global-id" do %>
	      <span class="fas fa-search"></span>
	      <% end %>
	    </span>
	  </div>
	</th>
        <th>
          <%= button_tag title: "link bib by global id",class: "btn btn-default" do %>
            <span class="far fa-save"></span>
          <% end %>
        </th>
      <% end %>
    <tr>
  </tfoot>
</table>
<%= link_to content_tag(:span, nil, class: "fas fa-pencil-alt"), '#', onclick: "$('#bib-bundle-form').submit();", class: "btn btn-default", title: "open multi-edit page with checked items" %>

<%= mantra "To let join, fill ID field and press save button.", :title => "Bibliographies related to <#{@specimen.name}>" %>

app/views/specimens/_file.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>name</th>
      <th></th>
      <th>spots</th>
      <th>global-id</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= form_with url:bundle_edit_attachment_files_path, id: "attachment-file-bundle-form" do %>
      <% @specimen.attachings.where(attachable_type: "Specimen").order("position ASC").each do |attaching| %>
        <% next unless attaching.attachment_file %>
        <tr>
          <% attachment_file = attaching.attachment_file %>
          <td>
            <%= check_box_tag("ids[]", attachment_file.id, checked: false, id: "ids_#{attachment_file.id}", class: "select-row") if can?(:update, attachment_file) %>
          </td>
          <td><%= attachment_file.decorate.picture(width: 70, height: 70, type: :thumb) %></td>
          <td><%= link_to_if can?(:read, attachment_file), list_title(attachment_file), attachment_file %></td>
          <td>
            <% if attachment_file.pdf? %>
              <%= link_to(image_pack_tag("icon_pdf_1.png", size: "24x24"), download_attachment_file_path(attachment_file.id), id: "file-#{attachment_file.id}-button") %>
            <% end %>
          </td>
          <td><%= attachment_file.spots.try!(:size) %></td>
          <td><%= attachment_file.try!(:global_id) %></td> 
          <td>
            <%= link_to move_to_top_attaching_path(attaching) + tab_param(__FILE__), method: :move_to_top ,title: "move to top" do %>
              <span class="fas fa-arrow-up"></span>
            <% end %>
          </td>
          <td>
            <%= link_to specimen_attachment_file_path(@specimen, attachment_file) + tab_param(__FILE__), method: :delete, title: "unlink attachment file", data: {confirm: t("confirm.unlink")} do %>
              <span class="fas fa-times"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <%= form_with model:AttachmentFile.new, url: specimen_attachment_files_path(@specimen), multipart: true do |f|%>
        <%= hidden_tabname_tag(__FILE__) %>
        <%= f.fields_for :record_property_attributes do |r| %>
          <%= r.hidden_field :user_id ,value: @current_user.id %>
        <% end %>
        <th><%= check_box_tag nil, nil, false, class: "select-row-all" %></th>
        <th colspan= "2">
          <%= f.file_field :data %>
        </th>
        <th>
          <%= f.button title:"add attachment file", class: "btn btn-default" do %>
            <span class="far fa-save"></span>
          <% end %>
        </th>
        <th>
        </th>
      <% end %>
      <%= form_with url:link_by_global_id_specimen_attachment_files_path(@specimen), method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
        <th>
	  <div class="input-group">
	    <%= text_field_tag :global_id, nil, id: "attachment-file-global-id", class: "form-control input-sm" %>
	    <span class="input-group-addon">
	      <%= link_to attachment_files_path(per_page: 5, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#attachment-file-global-id" do %>
	      <span class="fas fa-search"></span>
	      <% end %>
	    </span>
	  </div>
	</th>
        <th>
          <%= button_tag title: "link attachment file by global id", class: "btn btn-default" do %>
            <span class="far fa-save"></span>
          <% end %>
        </th>
      <% end %>
    </tr>
  </tfoot>
</table>
<%= link_to content_tag(:span, nil, class: "fas fa-pencil-alt"), '#', onclick: "$('#attachment-file-bundle-form').submit();", class: "btn btn-default", title: "open multi-edit page with checked items" %>
<%= mantra "To add data, specify a file with browse button and press save button.  To let join, fill ID field and press save button.  To edit, select with check box and press pencil button.", :title => "Files related to <#{@specimen.name}>" %>

app/views/specimens/_history.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<div class="pull-left">
place&nbsp;<%= link_to('quantity', quantity_history_specimen_path(@specimen))%>
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <% @specimen.paths.includes(:brought_in_by, :brought_out_by).each do |path| %>
  <% box = path.boxes.last %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= content_tag(:h3, history_title(path), class: "panel-title" ) %> 
    </div>
    <div class="panel-body">
      <div><%= timeline(path.brought_in_at, path.brought_out_at) %></div>
      <div>description: <%= best_in_place path, :note, :as => :input, :place_holder => 'Clik me to edit.', :html_attrs => { size: 50 } %></div>

      <% if box %>
          <% links = [] %>
          <% path.related_spots.each do |spot| %>
            <% next unless spot.attachment_file%>
            <% svg_link = link_to(spot_path(spot)) do %>
              <% spot.attachment_file.decorate.picture_with_spots(width:120, height:90, spots:[spot], with_cross: true) %>
            <% end %>
            <% links << content_tag(:div, svg_link, class: "col-xs-3 col-sm-3 col-md-3 col-lg-3") %>
          <% end %>
          <%= content_tag(:div, raw( links.join ), class: "row spot-thumbnails") %>
      <% end %>

    </div>
  </div>
  <% end %>
</div>

<%= mantra "Newer record above.", :title => "Relocation history of <#{@specimen.name}>" %>

app/views/specimens/_surface.html.erb
<% @specimen.full_surfaces.each do |surface| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= link_to(list_title(surface), surface, :title => "view map") %>
          <%= link_to specimen_surface_path(@specimen, surface) + tab_param(__FILE__), method: :delete, title: "unlink surface", data: {confirm: t("confirm.unlink")} do %>
            <span class="fas fa-times"></span>
          <% end %>
          <a href="#surface-<%= surface.id %>", data-toggle="collapse", aria-expanded="false", aria-control="surface-<%= surface.id %>", title = "show and hide spots belong to the surface">
            <span class="badge" style="float:right"><%= (surface.globe? ? 1 : surface.spots.size) %></span>
          </a>
  
          </div>
      <div class="panel-body collapse" id="surface-<%= surface.id %>">
      <% if surface.globe? %>
      <table class="table table-condensed table-striped">
        <thead>
          <tr>
            <th></th>
            <th>name</th>
            <th>latitude</th>
            <th>longitude</th>
            <th></th>
            <th>global-id</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <%= form_with url:bundle_edit_places_path, id: "place-bundle-form" do %>
          <% place = @specimen.place %>
          <tr>
            <td>
            </td>
            <td><%= link_to_if can?(:read, place), list_title(place), place %></td>
            <td><%= place.decorate.latitude_to_text %></td>
            <td><%= place.decorate.longitude_to_text %></td>
            <td></td>
            <td><%= place.try!(:global_id) %></td> 
            <td>
            </td>
          </tr>
        <% end %>
        </tbody>
        <tfoot>
          <tr>
          </tr>
        </tfoot>
      </table>
    <% else %>
      <table class="table table-condensed table-striped">
      <thead>
        <tr>
          <th></th>
          <th>name</th>
          <th>coordinate</th>
          <th>global-id</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
          <% surface.spots.each do |spot| %>
            <% spot = spot.decorate %>
            <% next unless spot %>
            <tr>
              <td>
              </td>
              <td><%= link_to_if can?(:read, spot), list_title(spot), spot %></td>
              <td><%= spot.decorate.world_xy_to_text %></td>
              <td><%= spot.try!(:global_id) %></td> 
              <td>
              </td>
            </tr>
          <% end %>
      </tbody>
    </table>
    <% end %>
    </div>
    </div>
  <% end %>
  
  <div class="panel panel-default">
  <div class="panel-heading">
  </div>
  <table class="table table-condensed">
    <tr>
    <td class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <%= form_with url:link_by_global_id_specimen_surfaces_path(@specimen), method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
          <div class="input-group"> 
          <%= text_field_tag :global_id, nil, id: "surface-global-id", :placeholder => "input ID", class: "form-control input-sm" %>
          <span class="input-group-addon">
            <%= link_to surfaces_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#surface-global-id" do %>
              <span class="fas fa-search"></span>
            <% end %>
          </span>
  
          </div>
            <%= button_tag title: "link surface by global id", class: "btn btn-default" do %>
              <span class="far fa-save"></span>
            <% end %>
      <% end %>
    </td>
    <td class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <%= form_with model:Surface.new, url: specimen_surfaces_path(@specimen) do |f|%>
          <%= hidden_tabname_tag(__FILE__) %>
          <%= f.text_field :name, :placeholder => "input name", class: "form-control input-sm" %>
            <%= f.button title:"add surface", class: "btn btn-default" do %>
              <span class="far fa-save"></span>
            <% end %>
        <% end %>
    </td>
    </tr>
  </table>
  </div>