config/routes.rb
  end

  concern :link_by_global_id do
    collection do
      post :link_by_global_id
    end
  end

  concern :inventory do
    member do
      post :inventory
    end
  end

  concern :multiple do
    collection do
      get :multiple_new
      post :multiple_create
    end
  end

  concern :sesar_upload do
    member do
      post :sesar_upload
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :records, only: %i[show]
      resources :spots
      resources :surfaces do
        resources :spots, concerns: [:link_by_global_id], only: [:index, :show, :create, :update, :destroy], controller: "surface_spots"
      end
    end
  end

  resources :records, { id: /((?!\.(html$|json$|xml$|pml$)).)*/ } do
    member do
      get 'record_property' => 'records#property'
      get 'casteml'
      get 'ancestors'
      get 'descendants'
      get 'self_and_descendants'
      get 'pmlame'
      get 'root'
      get 'parent'
      get 'daughters'
      get 'siblings'
      get 'self_and_siblings'
      get 'families'
      put :dispose
      patch :dispose
      put :restore
      patch :restore
      put :lose
      patch :lose
      put :found
      patch :found
      put :publish
      patch :publish
    end
  end

  resources :specimens, concerns: [:bundleable, :reportable, :sesar_upload], except: [:new] do
    member do
      get :quantity_history
      get :family
      get :picture
      get :map
      get :property
      get :detail_edit
      get :chemistries
      get :place, action: :show_place
      post :place, action: :create_place
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "specimen" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "specimen" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "specimen" }
    resources :daughters, concerns: [:link_by_global_id], only: [:index, :create,:update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "specimen" }
    resources :surfaces, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/surfaces", defaults: { parent_resource: "specimen" }
  end

  resources :divide_specimens, only: [:update] do
    member do
      put :loss
    end
  end

  resources :divides, only: [:edit, :update, :destroy] do
    member do
      put :loss
    end
  end

  resources :paths, only: [:update]

  resources :boxes, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :property
      get :tree_node
      get :list_for_print
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "box" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "box" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "box" }
    resources :specimens, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "box", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "box", association_name: "children" }
  end

  resources :places, concerns: [:bundleable, :reportable] do
    member do
      get :map
      get :property
    end
    collection do
      post :import
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "place" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id],only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "place" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "place" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "place", association_name: "specimens" }
  end

  resources :analyses, concerns: :bundleable do
    member do
      get :picture
      get :property
      get :casteml
    end
    collection do
      post :import
      get :table
      get :castemls
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "analysis" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "analysis" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "analysis" }
    resources :chemistries, concerns: [:multiple],only: [:index, :create, :update, :destroy], controller: "nested_resources/chemistries"
  end

  resources :bibs, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :map
      get :property
      get :specimens_detail
      put :publish
    end
    collection do
      get :download_to_tex
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "bib" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "bib", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "bib", association_name: "boxes" }
    resources :places, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/places", defaults: { parent_resource: "bib", association_name: "places" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "bib", association_name: "analyses" }
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "bib" }
    resources :tables, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/tables", defaults: { parent_resource: "bib" }
    resources :surfaces, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/surfaces", defaults: { parent_resource: "bib" }
  end

  resources :surfaces, concerns: [:bundleable, :reportable] do
    member do
      get :family
      get :picture
      get :property
      get :map
      get :layer
      get :image
      get :show_bibs
      get :show_specimens
      get :show_spot_specimens
      post 'tiles'
      post 'scale'
    end
    resources :images, concerns: [:link_by_global_id], only: [:index, :show, :create, :update, :destroy], controller: "surface_images" do
      member do
        get :family
        get :svg
        get :zooms
        get :map
        get :fits_image
        post 'move_to_top'
        post 'move_to_bottom'
        post 'move_higher'
        post 'move_lower'
        post 'insert_at'
        post 'choose_as_base'
        post 'unchoose_as_base'
        post 'tiles'
        get :calibrate
        get :calibrate_svg
        post 'layer'
      end
    end
    resources :spots, only: [:index, :create, :update, :destroy], controller: "nested_resources/spots"
    resources :layers, only: [:show, :create, :edit, :update, :destroy], controller: "surface_layers" do
      member do
        get :map
        get :calibrate
        get :images
        post 'move_to_top'
        post 'move_to_bottom'
        post 'move_higher'
        post 'move_lower'
        post 'tiles'
        put 'check'
        put 'uncheck'
        put 'toggle_visible'

app/models/box_type.rb
class BoxType < ApplicationRecord
  has_many :boxes

  validates :name, presence: true, length: {maximum: 255}
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  respond_to :html, :xml, :json
  before_action :find_resource, except: [:index, :create, :show, :bundle_edit, :bundle_update, :download_card, :download_bundle_card, :download_label, :download_bundle_label]
  before_action :find_resources, only: [:bundle_edit, :bundle_update, :download_bundle_card, :download_bundle_label]
  load_and_authorize_resource

  def index
    @search = Box.includes(:parent).readables(current_user).ransack(params[:q])
    @search.sorts = "updated_at DESC" if @search.sorts.empty?
    @boxes = @search.result.includes(:box_type).page(params[:page]).per(params[:per_page])
    respond_with @boxes
  end

  def show
    # @contents_search = Path.search(exists_at: Date.today.strftime("%Y%m%d"))
    # @contents_search.sorts = "path ASC"
    # @contents = Path.none
    # @contents = @contents.page(1).per(10)
    #if params[:q]
    separator = "-----"
    @button_action_selection_items = ["", "recent", "snapshot", separator]
    duration_numbers = [1]
    ["in/out from", "integ from", "diff from" ].each do |prefix|
      ["day", "week", "month", "year"].each do |str|
          duration_numbers.each do |num| 
            @button_action_selection_items << "#{prefix} #{num} #{str.pluralize(num)} ago"
          end
      end
    end
    @button_action_selection_items = @button_action_selection_items.map{|item| [item, item]}

    params[:q] = {} unless params[:q]

    if !(params[:dst_date].blank?)
      @dst_date = params[:dst_date]
    else
      @dst_date = Date.today.strftime("%Y-%m-%d")
    end

    if !(params[:src_date].blank?)
      @src_date = params[:src_date]
    else
      ddate = Date.strptime(@dst_date, "%Y-%m-%d")
      if m = /from (\d*) (.*) ago/.match(params[:button_action])
        sdate = convert_date(ddate, m[1], m[2])
      else
        oldest = Path.order(brought_in_at: :asc).first
        if oldest
          sdate = oldest.brought_in_at
        else
          sdate = convert_date(ddate, "10", "years")
        end
      end
      @src_date = sdate.strftime("%Y-%m-%d")
    end

    if Time.zone.parse(@dst_date).today?
      dst_date_time = Time.zone.now
    else
      dst_date_time = Time.zone.parse(@dst_date).end_of_day
    end

    default_sorts = "path ASC"
    if params[:button_action].blank? || params[:button_action] == separator
      @contents_search = Path.ransack(params[:q])
      @contents_search.sorts = "path ASC"
      @contents = Path.none
      @contents = @contents.page(params[:page]).per(params[:per_page])
    else
      case params[:button_action]
      when /diff/
        @contents_search = Path.diff(@box, @src_date, dst_date_time).ransack(params[:q])
      when /integ/
        @contents_search = Path.integ(@box, @src_date, dst_date_time).ransack(params[:q])
      when /snapshot/
        @contents_search = Path.snapshot(@box, dst_date_time).ransack(params[:q])
      else
        # in/out
        @contents_search = Path.change(@box, @src_date, dst_date_time).ransack(params[:q])
        default_sorts = ["brought_at DESC", "sign ASC"]
      end
      @contents_search.sorts = default_sorts if @contents_search.sorts.empty?
      @contents = @contents_search.result
      #@contents = @contents.current if @contents_search.conditions.empty?
      @contents = @contents.page(params[:page]).per(params[:per_page])
    end
    @box = Box.includes(children: [:record_property, :box_type], specimens: [:record_property, :analyses, :physical_form]).find(params[:id]).decorate
    respond_with @box
  end

  def edit
    respond_with @box, layout: !request.xhr?
  end

  def create
    @box = Box.new(box_params)
    @box.save
    respond_with @box
  end

  def update
    @box.update(box_params)
    respond_with @box
  end

  def destroy
    @box.destroy
    respond_with @box
  end

  def list_for_print
    respond_with @box, layout: !request.xhr?
  end

  def family
    respond_with @box, layout: !request.xhr?
  end

  def picture
    respond_with @box, layout: !request.xhr?
  end

  def property
    respond_with @box, layout: !request.xhr?
  end

  def tree_node
    record_property_id = params[:record_property_id].to_i
    klass = params[:klass].constantize
    depth = params[:depth].to_i + 1
    object = RecordProperty.find(record_property_id).datum.decorate
    render json: { tree_node: object.tree_nodes(klass, depth) }
  end

  def bundle_edit
    respond_with @boxes
  end

  def bundle_update
    @boxes.each { |box| box.update(box_params.only_presence) }
    render :bundle_edit
  end

  def download_card
    report = Box.find(params[:id]).build_card
    send_data(report.generate, filename: "box.pdf", type: "application/pdf")
  end

  def download_bundle_card
    method = (params[:a4] == "true") ? :build_a_four : :build_cards
    report = Box.send(method, @boxes)
    send_data(report.generate, filename: "boxes.pdf", type: "application/pdf")
  end

  def download_label
    box = Box.find(params[:id])
    send_data(box.build_label, filename: "box_#{box.id}.label", type: "text/label")
  end

  def download_bundle_label
    label = Box.build_bundle_label(@boxes)
    send_data(label, filename: "boxes.label", type: "text/label")
  end
  
  private

  def box_params
    params.require(:box).permit(
      :name,
      :parent_global_id,
      :parent_id,
      :position,
      :path,
      :box_type_id,
      :quantity,
      :quantity_unit,
      :tag_list,
      :user_id,
      :description,
      :group_id,
      :published,
      :fixed_in_box,
      record_property_attributes: [
        :id,
        :global_id,
        :user_id,
        :group_id,
        :owner_readable,
        :owner_writable,
        :group_readable,
        :group_writable,
        :guest_readable,
        :guest_writable,
        :published,
        :lost
      ]
    )
  end

  def find_resource
    @box = Box.find(params[:id]).decorate
  end

  def find_resources
    @boxes = Box.where(id: params[:ids])
  end

  def convert_date(date, value, unit)
    case unit
    when "day", "days"
      date.days_ago(value.to_i)
    when "week", "weeks"
      date.weeks_ago(value.to_i)
    when "month", "months"
      date.months_ago(value.to_i)
    when "year", "years"
      date.years_ago(value.to_i)
    else
      date.days_ago(1)
    end
  end

end

app/views/boxes/_bib.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th colspan= "2">name</th>
      <th>global-id</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= form_with url:bundle_edit_bibs_path, id: "bib-bundle-form" do %>
      <% @box.bibs.each do |bib| %>
        <tr>
          <td>
              <%= check_box_tag("ids[]", bib.id, false, {id: "ids_#{bib.id}", class: "select-row"}) if can?(:update, bib) %>
            </td>
          <td colspan="2"><%= link_to_if can?(:read, bib), list_title(bib), bib %></td>
          <td><%= bib.try!(:global_id) %></td>
          <td>
            <%= link_to box_bib_path(@box,bib) + tab_param(__FILE__), method: :delete ,title: "unlink bib",data: {confirm: t("confirm.unlink")} do %>
              <span class="fas fa-times"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
     <%= form_with model:Bib.new, url: box_bibs_path(@box) do |f|%>
        <%= hidden_tabname_tag(__FILE__) %>
        <th><%= check_box_tag nil, nil, false, class: "select-row-all" %></th>
        <th><%#= f.text_field :name, class: "form-control input-sm" %></th>
        <th>
          <%#= f.button title:"add bib",class: "btn btn-default" do %>
            <%#<span class="far fa-save"></span> %>
          <%# end %>
        </th>
      <% end %>
    <%= form_with url:link_by_global_id_box_bibs_path(@box), method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
        <th>
	  <div class="input-group">
	    <%= text_field_tag :global_id, "", id: "bib-global-id", class: "form-control input-sm" %>
	    <span class="input-group-addon">
	      <%= link_to bibs_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#bib-global-id" do %>
	      <span class="fas fa-search"></span>
	      <% end %>
	    </span>
	  </div>
	</th>
        <th>
          <%= button_tag title: "link bib by global id",class: "btn btn-default" do %>
            <span class="far fa-save"></span>
          <% end %>
        </th>
      <% end %>
    <tr>
  </tfoot>
</table>
<%= link_to content_tag(:span, nil, class: "fas fa-pencil-alt"), '#', onclick: "$('#bib-bundle-form').submit();", class: "btn btn-default", title: "open multi-edit page with checked items" %>
<%= mantra "To let join, fill ID field and press save button.", :title => "Bibliographies related to <#{@box.name}>" %>

app/views/boxes/_box.html.erb
<tr>
  <td><%= check_box_tag("ids[]", box.id, checked, id: "ids_#{box.id}", class: "select-row") if can?(:update, box) %></td>
  <td><%= link_to box.attachment_image_files.first.decorate.picture(width: 70, height: 70, type: :thumb), box.attachment_image_files.first if box.attachment_image_files.present? %></td>
  <td><%= link_to list_title(box), box %></td>
  <td><%= link_to box.parent.name,box.parent if box.parent %></td>
  <td><%= box.box_type.try!(:name) %></td>
  <%= td_if_expand box.tag_list %>
  <%= td_if_expand box.user.try!(:username) %>
  <td><%= box.group.try!(:name) %></td>
  <%= td_if_expand difference_from_now(box.published_at) %>
  <td><%= difference_from_now(box.updated_at) %></td>
  <%= td_if_expand difference_from_now(box.created_at) %>
</tr>
<%= mantra "Boxes rerated to <bench-container>.To upload a new box, fill in the columns of name and box-type. To link an existing box to <bench-container>, fill in the column of ID." %> 

app/views/boxes/_box.modal.erb
<tr>
  <td>
    <%= button_tag class: "btn btn-default btn-xs determine", "data-id" => box.global_id do %>
    <span class="fas fa-link"></span>
    <% end %>
  </td>
  <td><%= link_to box.name, box_path(box, format: :modal), "data-toggle" => "modal", "data-target" => "#show-modal" %></td>
  <td><%= box.parent.try!(:name) %></td>
  <td><%= box.box_type.try!(:name) %></td>
  <td><%= box.group.try!(:name) %></td>
  <td><%= difference_from_now(box.updated_at) %></td>
</tr>

app/views/boxes/_specimen.html.erb
<div class="btn-group">
  <a href="#display-type-html" class="btn radio-button-group">html</a>
  <a href="#display-type-tex" class="btn radio-button-group">tex</a>
  <%= link_to "list", list_for_print_box_path(@box), class:"btn radio-button-group" %>
</div>
<div class="display-type">
  <div id="display-type-html">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="panel panel-default">
	  <div class="panel-heading">
	  </div>
	  <table class="table table-condensed">
	    <tbody>
          <%= form_with url:bundle_edit_specimens_path, id: "specimen-bundle-form" do %>
		    <% @box.specimens.each do |specimen| %>
			  <% specimen = specimen.decorate %>
		  	  <%= render partial: "list_specimen", :locals => { specimen: specimen } %>
			<% end %>
          <% end %>
	    </tbody>
	  </table>
	</div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <%= link_to content_tag(:span, nil, class: "fas fa-pencil-alt"), '#', onclick: "$('#specimen-bundle-form').submit();", class: "btn btn-default", title: "open multi-edit page with checked items" %>
	<div class="panel panel-default">
	  <div class="panel-heading">
	  </div>
	  <table class="table table-condensed">
	    <tr>
	      <td class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
		<%= form_with url:link_by_global_id_box_specimens_path(@box), method: :post do %>
		  <%= hidden_tabname_tag(__FILE__) %>
		  <div class="input-group">
		    <%= text_field_tag :global_id, nil, id: "specimen-global-id", :placeholder => "input ID", class: "form-control input-sm" %>
		    <span class="input-group-addon">
		      <%= link_to specimens_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#specimen-global-id" do %>
			<span class="fas fa-search"></span>
		      <% end %>
		    </span>

		  </div>
		  <%= button_tag title: "link specimen by global id", class: "btn btn-default" do %>
                    <span class="far fa-save"></span>
		  <% end %>
		<% end %>
	      </td>
	      <td class="col-xs-6 col-sm-6 col-md-6 col-lg-6">

        <%= form_with model:Specimen.new, url: box_specimens_path(@box) do |f|%>
		  <%= hidden_tabname_tag(__FILE__) %>
		  <%= f.text_field :name, :placeholder => "input name", class: "form-control input-sm" %>
		  <%= f.select :physical_form_id, PhysicalForm.pluck(:name, :id), { prompt: "select physical form" }, class: "form-control input-sm" %>
		  <%= f.text_field :quantity, :placeholder => "input quantity", class: "form-control input-sm" %>
		  <%= f.text_field :quantity_unit, :placeholder => "input quantity unit", class: "form-control input-sm" %>
		  <%= f.button title:"add specimen file", class: "btn btn-default" do %>
                    <span class="far fa-save"></span>
		  <% end %>
		<% end %>
	      </td>
	    </tr>
	  </table>
	</div>
      </div>
    </div>
  </div>
  <div class="hidden" id="display-type-tex">
    <pre><code><%= @box.to_tex(@alias_specimen) %></code></pre>
  </div>
</div>
<%= mantra "To let join, fill ID field and press save button.  To create new, fill fields and press save button.", :title => "#{@alias_specimens.capitalize} contained in <#{@box.name}>" %> 

app/views/boxes/edit.html.erb
<%= form_with model:@box, local: false, format: :json, html: { id: "edit_box_#{@box.id}", class: "update", role: "form" } do |f| %>
  <div class="form-group form-group-sm">
    <%= f.label :name, class: "small" %>
    <%= f.text_field :name, class: "form-control input-sm" %>
  </div>
  <div class="form-group form-group-sm">
    <%= f.label :box_type_id, class: "small" %>
    <%= f.select :box_type_id, BoxType.pluck(:name, :id), {include_blank: true}, class: "form-control input-sm" %>
  </div>
  <div class="form-group form-group-sm">
    <%= f.label :quantity, class: "small" %>
    <%= f.text_field :quantity, class: "form-control input-sm" %>
  </div>
  <div class="form-group form-group-sm">
    <%= f.label :quantity_unit, class: "small" %>
    <%= f.text_field :quantity_unit, class: "form-control input-sm" %>
  </div>
  <div class="form-group form-group-sm">
    <%= f.label :tag_list, class: "small" %>
    <%= f.text_field :tag_list, class: "form-control input-sm" %>
  </div>
  <div class="form-group form-group-sm">
    <%= f.label :parent_global_id, class: "small" %>
    <div class="input-group">
      <%= f.text_field :parent_global_id, id: "box_parent_global_id", class: "form-control input-sm" %>
      <span class="input-group-addon">
	<%= link_to boxes_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#box_parent_global_id" do %>
	<span class="fas fa-search"></span>
	<% end %>
      </span>
    </div>
  </div>
  <div class="form-group form-group-sm">
    <%= f.label :description, class: "small" %>
    <%= f.text_area :description, class: "form-control input-sm" %>
  </div>
  <div class="form-group form-group-sm">
    <label class="small">Fixed in box</label>
    <%= f.label :fixed_in_box, class: "checkbox-inline" do %>
      <%= f.check_box :fixed_in_box %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-default" do %>
  <span class="far fa-save"></span>
  <% end %>
<% end %>

<%= javascript_tag do %>
  $(document).on("succeed.ajaxForm", "#edit_box_<%= @box.id %>", function() {
    location.href="<% box_path(@box) %>";
  });
<% end %>

app/views/boxes/family.html.erb
<div>
  <% if @box.attachment_files.present? %>
    <%= @box.primary_picture_with_link %>
  <% end %>
</div>
<div id="family-tree">
  <%= @box.family_tree %>
</div>

app/views/boxes/picture.html.erb
<div class="spot-viewer">
  <%= hidden_field_tag nil, @box.global_id, class: "target-uid" %>
  <%= content_tag :svg, nil, class: "spot-canvas", width: 250, height: 250 %>
  <div id="family-tree">
    <%= @box.attachment_files.first.decorate.family_tree %>
  </div>

  <%= form_with model:Spot.new, url: attachment_file_spots_path(@box.attachment_files.first) do |f| %>
    <table>
      <tr>
        <td><%=icon_tag("crosshairs") %> (link ID </td>
          <td>
            <div class="input-group">
              <%= f.text_field :target_uid, id: "spot_target_uid", class: "form-control input-sm" %>
              <span class="input-group-addon">
                <%= link_to records_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#spot_target_uid",  id: "record-property-search" do %>
                  <span class="fas fa-search"></span>
                <% end %>
              </span>
            </div>
          </td>
        <td>)</td>
        <td>
          <%= f.hidden_field :spot_x ,value: "0" %>
          <%= f.hidden_field :spot_y ,value: "0" %>
          <%= f.hidden_field :radius_in_percent ,value: "2" %>
          <%= f.hidden_field :stroke_color ,value: "blue" %>
          <%= f.hidden_field :fill_color ,value: "blue" %>
          <%= f.hidden_field :opacity ,value: "0" %>
          <%= f.hidden_field :with_cross ,value: "false" %>
          <%= f.button title:"add new spot", class: "btn btn-default" do %>
            <span class="far fa-save"></span>
          <% end %>
        </td>
      </tr>
    </table>
  <% end %>
  <% @box.attachment_image_files.each_slice(4) do |files| %>
  <div class="row spot-thumbnails">
    <% files.each do |file| %>
    <div class="col-lg-3">
      <%= link_to attachment_file_path(file, format: :svg), remote: true, class: "thumbnail" do %>
        <%= image_tag file.path %>
      <% end %>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

<%= javascript_tag do %>
  $("div.spot-viewer").spotViewer();
  $(document).on("submit", "#new_spot", function() {
    var center = $("div.spot-viewer").spotViewer("center");
    $("#spot_spot_x").val(center.left);
    $("#spot_spot_y").val(center.top);
  });
<% end %>